spring:
  application:
    name: chap06-file-upload-lecture-source

  servlet:
    multipart:
      location: C:\SWCAMP22\06_SpringFramework\10_LimWonSuk\uploadFiles # ?? ?? ??
      max-file-size: 10MB # ?? ??? ?? ??
      max-request-size: 10MB # ?? ?? ?? ??

