Spring:
  application:
    name: chap06-file-upload-lecture-source

  servlet:
    multipart:
      location: /Users/gangseonghun/desktop # ?? ?? ??
      max-file-size: 10MB # ?? ??? ?? ??
      max-request-size: 10MB # ?? ?? ?? ??

